{% set name = "ska-gridder-nifty-cuda" %}

package:
  name: {{ name|lower }}
  version: 0.0.11

env:
  LABEL: main

requirements:
  build: 
    - {{ compiler('cxx') }}
  host:
    - python=3.9
    - pip
    - {{ pin_compatible('numpy') }}
  run:
    - python=3.9
    - {{ pin_compatible('numpy') }}

build:
  script: "pip install git+http://gitlab.com/ska-telescope/sdp/ska-gridder-nifty-cuda.git@sim-874-python-wrapper#subdirectory=python"

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-gridder-nifty-cuda
  license: Custom
  license_family: Other
  copyright: 
    - Copyright 2021 Adam Campbell, Anthony Griffin, Andrew Ensor, Seth Hall
    - Copyright 2021 High Performance Computing Research Laboratory, Auckland University of Technology (AUT)
  summary: 'NIFTy Gridder - CUDA implementation'
  description: |
   This repository contains of an in-progress parallelised prototype of the Numerical Information Field Theory (NIFTy) based gridding algorithm for wide-field radio telescope imaging systems. The NIFTy gridder is a composition of an analytical exponential of semicircle gridding kernel (as presented in this research paper), and the improved w-stacking method (as presented on page 139 in this thesis). This implemention approximately follows a C++ implementation of NIFTy gridder (available from this repository).
  doc_url: https://gitlab.com/ska-telescope/sdp/ska-gridder-nifty-cuda/-/blob/sim-874-python-wrapper/README.md
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-gridder-nifty-cuda/-/tree/sim-874-python-wrapper

extra:
  recipe-maintainers:
    - Vincenzo Timmel