name: Conda Build Package Ska-Gridder-Nifty-Cuda

env:
  VERSION: 0.0.11
  LABEL: main
  #LABEL: dev

on:
  push:
    branches:
      - '[0-9]*.[0-9]*.[dev0-9]*'
  pull_request:
    branches:
      - '[0-9]*.[0-9]*.[dev0-9]*'
  workflow_dispatch:

jobs:
  conda-build:
    runs-on: ubuntu-20.04
    container: ghcr.io/i4ds/mambabuild-docker:latest

    steps:
      - name: Install conda build
        run: |
          conda config --append channels conda-forge
          conda config --append channels i4ds
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Conda
        run: |
          cd conda
          conda build .
      - name: Test
        run : |
          conda install --use-local ska-gridder-nifty-cuda
          python test.py
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /opt/conda/conda-bld/noarch/ska-gridder-nifty-cuda-*.tar.bz2 --label $LABEL